# Generated by Django 4.2.6 on 2023-12-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='MOV',
        ),
    ]
