# Generated by Django 4.2.6 on 2023-12-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam1', '0002_rename_movie_mov'),
    ]

    operations = [
        migrations.CreateModel(
            name='kk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='MOV',
        ),
    ]
