# Generated by Django 4.2.6 on 2023-12-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam1', '0003_kk_delete_mov'),
    ]

    operations = [
        migrations.AddField(
            model_name='kk',
            name='description',
            field=models.CharField(default='s', max_length=10),
        ),
    ]
