# Generated by Django 4.2.6 on 2023-12-18 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam1', '0006_streamplatform_watchlist_delete_kk'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Watchlist', to='exam1.streamplatform'),
            preserve_default=False,
        ),
    ]
